apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dispatcher
  namespace: nthulab
spec:
  template:
    spec:
      serviceAccountName: dispatcher-service-account
      volumes:
        - name: dispatcher-config-volume
          configMap:
            name: dispatcher-config
      containers:
        - name: dispatcher-container
          image: ghcr.io/deeeelin/ssis-dispatcher:main
          ports:
            - containerPort: 8080
          imagePullPolicy: Always 
          volumeMounts:
              - name: dispatcher-config-volume
                mountPath: /etc/dispatcher-config
                readOnly: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher-service-account
  namespace: nthulab

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dispatcher
  namespace: nthulab
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dispatcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dispatcher
subjects:
  - kind: ServiceAccount
    name: dispatcher-service-account
    namespace: nthulab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
  namespace: nthulab
data:
  service-namespace: nthulab
  inference-image: ghcr.io/llshang/tgi_custom:latest
  gpu-resource-config: |
    nvidia.com/gpu-1gb
    nvidia.com/gpu-2gb
    nvidia.com/gpu-3gb
    nvidia.com/gpu-4gb
    nvidia.com/gpu-5gb
    nvidia.com/gpu-6gb
    nvidia.com/gpu-7gb
    nvidia.com/gpu-8gb
    nvidia.com/gpu-9gb
    nvidia.com/gpu-10gb
    nvidia.com/gpu-11gb
    nvidia.com/gpu-12gb
    nvidia.com/gpu-13gb
    nvidia.com/gpu-14gb
    nvidia.com/gpu-15gb
    nvidia.com/gpu-16gb
    nvidia.com/gpu-17gb
    nvidia.com/gpu-18gb
    nvidia.com/gpu-19gb
    nvidia.com/gpu-20gb
    nvidia.com/gpu-21gb
    nvidia.com/gpu-22gb
    nvidia.com/gpu-23gb
    nvidia.com/gpu-24gb
    nvidia.com/gpu-25gb
    nvidia.com/gpu-26gb
    nvidia.com/gpu-27gb
    nvidia.com/gpu-28gb
    nvidia.com/gpu-29gb
    nvidia.com/gpu-30gb
    nvidia.com/gpu-31gb
    nvidia.com/gpu-32gb

  mps-active-thread-percentage-config: | # for mps mode to set the active thread percentage(compute SM resource)
    nvidia.com/gpu-1gb: 3
    nvidia.com/gpu-2gb: 6
    nvidia.com/gpu-3gb: 9
    nvidia.com/gpu-4gb: 12
    nvidia.com/gpu-5gb: 15
    nvidia.com/gpu-6gb: 18
    nvidia.com/gpu-7gb: 21
    nvidia.com/gpu-8gb: 25
    nvidia.com/gpu-9gb: 28
    nvidia.com/gpu-10gb: 31
    nvidia.com/gpu-11gb: 34
    nvidia.com/gpu-12gb: 37
    nvidia.com/gpu-13gb: 40
    nvidia.com/gpu-14gb: 43
    nvidia.com/gpu-15gb: 46
    nvidia.com/gpu-16gb: 50
    nvidia.com/gpu-17gb: 53
    nvidia.com/gpu-18gb: 56
    nvidia.com/gpu-19gb: 59
    nvidia.com/gpu-20gb: 62
    nvidia.com/gpu-21gb: 65
    nvidia.com/gpu-22gb: 68
    nvidia.com/gpu-23gb: 71
    nvidia.com/gpu-24gb: 75
    nvidia.com/gpu-25gb: 78
    nvidia.com/gpu-26gb: 81
    nvidia.com/gpu-27gb: 84
    nvidia.com/gpu-28gb: 87
    nvidia.com/gpu-29gb: 90
    nvidia.com/gpu-30gb: 93
    nvidia.com/gpu-31gb: 96
    nvidia.com/gpu-32gb: 100
---

#---
# Register a PV to require storage on disk
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: knative-pv
#  namespace: nthulab
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: manual
#  hostPath:
#    path: /net/to/storage ex. /net/storage149/autofs/css89
#
#--- 
# Use a claim (similar to role binding) for a PV, then a pod uses this PV as a volume and calls it
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: knative-pv-claim
#  namespace: nthulab
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 100Gi
#  storageClassName: manual
