name: Build Dispatcher Image

on:
  push:
    branches:
      - '*'
    paths:
      - '**.go'
      - '**.yaml'
      - 'Dockerfile'
      - '.github/workflows/*'
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
 
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: Set configurations
            run: |
              sed -i "s/^GITHUB_USER=.*/GITHUB_USER=${GITHUB_ACTOR}/" ./makefile
              sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${GITHUB_REF_NAME}/" ./makefile
              sed -i "s|image: ghcr.io/deeeelin/ssis-dispatcher:main|image: ghcr.io/${GITHUB_ACTOR}/ssis-dispatcher:${GITHUB_REF_NAME}|" ./configuration.yaml

              cat ./makefile
              cat ./configuration.yaml

          - name: Commit and Push Changes
            run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "Customized configuration.yaml and makefile for ${GITHUB_REF_NAME} branch"
              git push -f origin ${GITHUB_REF_NAME}:${GITHUB_REF_NAME}-deployment
          
          - name: 'Build Image'
            shell: bash
            run: |
              make build

          # - name: Login and Deploy to Server
          #   run: |
          #       mkdir -p ~/.ssh
          #       echo -e "Host ${SSH_HOST_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          #       echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          #       chmod 600 ~/.ssh/id_rsa

          #       ssh -i ~/.ssh/id_rsa ${SSH_HOSTNAME}@${SSH_HOST_IP} 'ls'

          #       # scp -i ~/.ssh/id_rsa -r . ${SSH_HOSTNAME}@${SSH_HOST_IP}:/tmp/ssis-dispatcher
          #       # ssh -i ~/.ssh/id_rsa ${SSH_HOSTNAME}@${SSH_HOST_IP}

          #       # cd /tmp/ssis-dispatcher
          #       # make deploy
          #       # rm -r /tmp/ssis-dispatcher     
          #   env:
          #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #     SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          #     SSH_HOST_IP: ${{ secrets.SSH_HOST_IP }}

                

